import "../globals.css";
import Footer from "@/components/footer";

export default function Login() {

    const termsText = `
        Last Updated: 2024.12.26.

1. Introduction

Frameza ("Frameza," "we," "us," or "our") is committed to protecting the privacy of our users. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our AI video generation service (collectively, the "Service"). Please read this Privacy Policy carefully. By accessing or using our Service, you acknowledge that you have read, understood, and agree to be bound by the terms of this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not access the site or use our service.

2. Information We Collect

We may collect information about you in a variety of ways. The information we may collect includes:

Personal Data:

Account Information: When you register for an account, we collect your email address and a password. Your password is cryptographically hashed and stored securely. We use MongoDB Atlas as our database service provider. You can learn more about MongoDB Atlas' security practices here: https://www.mongodb.com/resources/products/capabilities/mongodb-atlas-security

Payment Information: We use Stripe to process payments for our Service. We do not store your full payment card details on our servers. Stripe handles your payment information in accordance with its own Privacy Policy, which you can review here: https://stripe.com/en-hu/privacy

Prompts and Videos: We collect the text prompts and initial video frames that you upload to use our video generation Service. We also temporarily store the videos generated by the AI.

Usage Data: We may automatically collect information about how you interact with the Service, such as your IP address, browser type, operating system, referring URLs, pages viewed, and the dates and times of your visits.

3. How We Use Your Information

We may use the information we collect from you for the following purposes:

To Provide and Maintain the Service: We use your information to create and manage your account, process your payments, generate videos based on your prompts, and provide customer support.

To Improve the Service: We use your prompts, generated videos, and usage data to train and improve our AI models, develop new features, and enhance the overall user experience.

To Communicate with You: We may use your email address to send you important updates about the Service, such as changes to our Terms of Service or this Privacy Policy, security alerts, and other administrative messages. We will also use your email to respond to your inquiries and requests.

For Legal Compliance: We may use your information to comply with applicable laws, regulations, legal processes, or governmental requests.

4. How We Share Your Information

We may share your information in the following circumstances:

With Third-Party Service Providers:

MongoDB Atlas: We use MongoDB Atlas to store user account data, including email addresses and hashed passwords.

Stripe: We use Stripe to process payments. Your payment information is transmitted directly to Stripe and is not stored on our servers.

Replicate: We use Replicate's API to generate videos. Your prompts and initial video frames are sent to Replicate for processing. Replicate may also collect data about your use of their service as described in their privacy policy. Replicate's Privacy Policy can be found here: https://replicate.com/privacy

With Your Consent: We may share your information with third parties if you have given us your explicit consent to do so.

For Legal Reasons: We may disclose your information if we are required to do so by law, such as to comply with a subpoena, court order, or other legal process. We may also disclose your information if we believe it is necessary to protect our rights, the safety of our users, or the public.

Business Transfers: In the event of a merger, acquisition, reorganization, sale of assets, bankruptcy, or similar event, your information may be transferred as part of that transaction. We will notify you via email and/or a prominent notice on our website of any change in ownership or uses of your personal information, as well as any choices you may have regarding your personal information.

5. Data Security

We take reasonable measures to protect your information from unauthorized access, use, or disclosure. We use industry-standard security practices, such as encryption and secure server infrastructure. However, no method of transmission over the internet or method of electronic storage is 100% secure. Therefore, we cannot guarantee the absolute security of your information.

6. Data Retention

We will retain your personal information for as long as your account is active or as needed to provide you with the Service. We will also retain your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements. We may retain anonymized or aggregated data indefinitely.

7. Your Data Rights (GDPR Compliance)

If you are a resident of the European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR). These rights include:

The Right to Access: You have the right to request a copy of the personal data we hold about you.

The Right to Rectification: You have the right to request that we correct any inaccurate or incomplete personal data we hold about you.

The Right to Erasure ("Right to be Forgotten"): You have the right to request that we delete your personal data under certain circumstances.

The Right to Restrict Processing: You have the right to request that we restrict the processing of your personal data under certain circumstances.

The Right to Data Portability: You have the right to receive your personal data in a structured, commonly used, and machine-readable format and to transmit that data to another controller.

The Right to Object: You have the right to object to the processing of your personal data under certain circumstances, including for direct marketing purposes.

To exercise these rights, please contact us at info@frameza.net. We will respond to your request within a reasonable timeframe and in accordance with applicable law.

8. Children's Privacy

Our Service is not intended for children under the age of 16. We do not knowingly collect personal information from children under 16. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us. If we become aware that we have collected personal information from a child under 16 without verification of parental consent, we will take steps to remove that information from our servers.

9. International Data Transfers

Frameza is based in Hungary. Your information, including personal data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

If you are located outside Hungary and choose to provide information to us, please note that we transfer the data, including personal data, to Hungary and process it there. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and applicable data protection laws, including GDPR. We rely on legally-provided mechanisms to lawfully transfer data across borders, such as using standard contractual clauses approved by the European Commission or obtaining your explicit consent.

10. Links to Other Websites

Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

11. Changes to This Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top. We may also notify you via email if the changes are material. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

12. Contact Us

If you have any questions about this Privacy Policy, please contact us:

By email: info@frameza.net
    `

    const lines = termsText.trim().split('\n');

    return (
        <>
        <h1>Privacy Policy</h1>
            <div>
                {lines.map((line, index) => (
                    <p key={index}>{line}</p>
                ))}
            </div>
        <Footer />
        </>
    )
}